[project]
name = "vectorstore-langchain-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.25",
    "langchain-chroma>=0.2.4",
    "langchain-community>=0.3.24",
    "langchain-openai>=0.3.19",
    "langchain-text-splitters>=0.3.8",
    "langgraph>=0.4.8",
]
